### ISSUE TITLE
e-mail pour les questionnaires

### ISSUE THREAD

**Issue by transcrow** [eaa-imd/seminaire-2018#8]
Bonjour,

Nous sommes des élèves de l’EAA-CIFOM, école d’arts de La Chaux-de-Fonds en Suisse. Nous réalisons une enquête sur les outils utilisés aujourd'hui dans la profession du design. Nous vous invitons à remplir ce questionnaire qui ne vous prendra pas plus de 5 minutes, pour nous aider dans la réalisation de ce projet. 

Les résultats seront publiés sur un site dédié, qui sera lancé à la fin du mois de juin.

Ci-dessous nous vous transmettons le lien pour ce questionnaire. Merci de le diffuser autour de vous afin que notre sondage soit le plus représentatif possible.

Nous vous souhaitons une très bonne journée, 
les élèves de 3e année Interactive Media Designer

Liens à cliquer:

- Ok, je remplis le questionnaire: https://designsurvey2018.typeform.com/to/VDskmj

- Ça m'intéresse, informez-moi quand le site sera en ligne: http://eepurl.com/dvbNFz

**Comment by mathiasliniger** [comment]
http://eepurl.com/dvbNFz

**Comment by ms-studio** [comment]
Je ferme ce ticket, puisque Vladimir a créé une nouvelle formulation:

https://github.com/eaa-imd/designtools/issues/10
